language: go
go:
  - "1.2.2"
  - master

before_install:
  - go get -t -v ./...

script:
  # go.mod is overwritten to avoid go version being part of the mod file, which fails tests on mismatching version
  - echo "module github.com/bnkamalesh/currency" > go.mod
  - go test -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /cmd)

after_success:
  - bash <(curl -s https://codecov.io/bash)